# Site settings
title: Your Site Title
email: your-email@example.com
description: >
  Kiez.nu - Gen Z Kiest
baseurl: "/kiez-web"
url: "https://scumstudios.github.io"
permalink: pretty

# Relative links settings
relative_links:
  enabled: true
  collections: true